/**
 * aiPrompt.js
 *
 * Pure utility — no React, no side effects, no API calls.
 * Builds a structured plain-text prompt that gives an AI tool
 * enough context about a Plainly project to continue work immediately.
 */

export const CONTENT_LIMIT = 12000 // characters; truncate file content beyond this

/**
 * The AI tools Continue with AI offers, and where "Open …" sends you.
 *
 * Every url is https. Plainly is served over https, so handing someone a
 * plaintext hop would be a downgrade for no benefit — if a tool genuinely has
 * no https address it doesn't belong in this list.
 *
 * `generic` is copy-only and never appears as a button; ContinueWithAI filters
 * it out. It exists so the handoff can be built without a tool chosen.
 */
export const AI_TOOLS = [
  {
    id: 'chatgpt',
    label: 'ChatGPT',
    url: 'https://chatgpt.com/',
  },
  {
    id: 'claude',
    label: 'Claude',
    url: 'https://claude.ai/code',
  },
  {
    id: 'gemini',
    label: 'Gemini',
    url: 'https://gemini.google.com/app',
  },
  {
    id: 'manus',
    label: 'Manus',
    url: 'https://manus.im/app/',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    url: 'https://www.deepseek.com/en/',
  },
  {
    id: 'generic',
    label: 'Generic AI',
    url: null, // copy-only; no tab opened
  },
]

/**
 * Build a structured project-context prompt ready to paste into any AI tool.
 *
 * @param {object} params
 * @param {string}   params.projectName         - Display name (spaces, not hyphens)
 * @param {string}   [params.description]       - Project description (may be empty)
 * @param {string}   params.repoName            - Raw GitHub repository name
 * @param {string[]} params.fileNames           - Names of all files in the project
 * @param {string}   [params.activeFileName]    - Name of the currently open file
 * @param {string}   [params.activeFileContent] - Full text of the currently open file
 * @param {string}   [params.latestSaveLabel]   - Most recent save-point label
 * @param {string}   [params.userInstruction]   - What the user wants the AI to do
 * @param {object}   [params.activeTask]        - Active task object from taskMemory
 * @param {string}   [params.projectInstructions] - Free-form instructions (from task notes)
 * @returns {string}
 */
export function buildProjectPrompt({
  projectName,
  description,
  repoName,
  fileNames = [],
  activeFileName,
  activeFileContent,
  latestSaveLabel,
  userInstruction,
  activeTask,
  projectInstructions,
}) {
  const lines = []

  // ── Header ─────────────────────────────────────────────────────────────────
  lines.push('# Project Context')
  lines.push('')
  lines.push(
    'This prompt was generated by Plainly, a plain-language interface for GitHub.',
    'It contains the full context of a project so you can continue working on it immediately.',
  )
  lines.push('')

  // ── Project identity ───────────────────────────────────────────────────────
  lines.push('## Project')
  lines.push('')
  lines.push(`**Name:** ${projectName || repoName || '(unnamed)'}`)
  lines.push(`**Repository:** ${repoName || '(unknown)'}`)

  if (description && description.trim()) {
    lines.push(`**Description:** ${description.trim()}`)
  }

  if (latestSaveLabel && latestSaveLabel.trim()) {
    lines.push(`**Latest save point:** ${latestSaveLabel.trim()}`)
  }

  lines.push('')

  // ── File list ──────────────────────────────────────────────────────────────
  lines.push('## Files in this project')
  lines.push('')

  if (fileNames.length === 0) {
    lines.push('(No files found in this project.)')
  } else {
    fileNames.forEach(name => {
      const marker = name === activeFileName ? ' ← currently open' : ''
      lines.push(`- ${name}${marker}`)
    })
  }

  lines.push('')

  // ── Currently open file ────────────────────────────────────────────────────
  if (activeFileName) {
    lines.push(`## Currently open file: ${activeFileName}`)
    lines.push('')

    if (!activeFileContent || activeFileContent.trim() === '') {
      lines.push('(This file is empty.)')
    } else if (activeFileContent.length > CONTENT_LIMIT) {
      const truncated = activeFileContent.slice(0, CONTENT_LIMIT)
      lines.push(truncated)
      lines.push('')
      lines.push(
        `[Content truncated at ${CONTENT_LIMIT.toLocaleString()} characters. ` +
        `The full file is ${activeFileContent.length.toLocaleString()} characters. ` +
        `Open the file in Plainly to see the complete version.]`
      )
    } else {
      lines.push(activeFileContent)
    }

    lines.push('')
  } else {
    lines.push('## Currently open file')
    lines.push('')
    lines.push('(No file is currently open. The project context above is the available information.)')
    lines.push('')
  }

  // ── Active update ──────────────────────────────────────────────────────────
  if (activeTask) {
    lines.push('## Current update')
    lines.push('')
    lines.push(`**Title:** ${activeTask.title}`)
    if (activeTask.goal && activeTask.goal.trim()) {
      lines.push(`**Goal:** ${activeTask.goal.trim()}`)
    }
    // Status labels for the new 9-state lifecycle
    const statusLabels = {
      planned:            'Planned',
      ready_for_ai:       'Ready for AI',
      sent_to_ai:         'Sent to AI',
      changes_detected:   'Changes detected',
      waiting_for_review: 'Waiting for review',
      ready_to_save:      'Ready to save',
      saved:              'Saved',
      needs_correction:   'Needs correction',
      paused:             'Paused',
      // legacy fallbacks
      'open':             'Open',
      'in-progress':      'In progress',
      'review':           'Review',
      'done':             'Done',
    }
    lines.push(`**Status:** ${statusLabels[activeTask.status] || activeTask.status}`)
    if (activeTask.notes && activeTask.notes.trim()) {
      lines.push(`**Notes:** ${activeTask.notes.trim()}`)
    }
    lines.push('')
  }

  // ── Project instructions (from task notes or freeform) ─────────────────────
  if (projectInstructions && projectInstructions.trim()) {
    lines.push('## Project instructions')
    lines.push('')
    lines.push(projectInstructions.trim())
    lines.push('')
  }

  // ── User instruction ───────────────────────────────────────────────────────
  lines.push('## Your task')
  lines.push('')

  const instruction = userInstruction && userInstruction.trim()
    ? userInstruction.trim()
    : 'Continue implementing this project while preserving the existing architecture and approach.'

  lines.push(instruction)
  lines.push('')

  // ── Continuation guidance ──────────────────────────────────────────────────
  lines.push('## Continuation guidance')
  lines.push('')
  lines.push(
    'Please begin your response by confirming your understanding of the project context above.',
    'Then proceed with the task. If any context is unclear or missing, ask before making assumptions.',
  )

  return lines.join('\n')
}
